# Generated by Django 2.1.7 on 2019-03-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('OrderItem', 'order_id', 'order')
    ]
